# Generated by Django 3.2.13 on 2022-04-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r1pos',
            field=models.CharField(default='1p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r1res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r2pos',
            field=models.CharField(default='1p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r2res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r3pos',
            field=models.CharField(default='1p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r3res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r4pos',
            field=models.CharField(default='1p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r4res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r5pos',
            field=models.CharField(default='1p', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertournamentrelation',
            name='r5res',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeirdTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('r4', models.IntegerField()),
                ('r5', models.IntegerField()),
                ('r6', models.IntegerField()),
                ('r1pos', models.CharField(max_length=2)),
                ('r2pos', models.CharField(max_length=2)),
                ('r3pos', models.CharField(max_length=2)),
                ('r4pos', models.CharField(max_length=2)),
                ('r5pos', models.CharField(max_length=2)),
                ('r6pos', models.CharField(max_length=2)),
                ('r1res', models.IntegerField()),
                ('r2res', models.IntegerField()),
                ('r3res', models.IntegerField()),
                ('r4res', models.IntegerField()),
                ('r5res', models.IntegerField()),
                ('r6res', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='OCMSLU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('r4', models.IntegerField()),
                ('r5', models.IntegerField()),
                ('r6', models.IntegerField()),
                ('r7', models.IntegerField()),
                ('r8', models.IntegerField()),
                ('r9', models.IntegerField()),
                ('r1pos', models.CharField(max_length=2)),
                ('r2pos', models.CharField(max_length=2)),
                ('r3pos', models.CharField(max_length=2)),
                ('r4pos', models.CharField(max_length=2)),
                ('r5pos', models.CharField(max_length=2)),
                ('r6pos', models.CharField(max_length=2)),
                ('r7pos', models.CharField(max_length=2)),
                ('r8pos', models.CharField(max_length=2)),
                ('r9pos', models.CharField(max_length=2)),
                ('r1res', models.IntegerField()),
                ('r2res', models.IntegerField()),
                ('r3res', models.IntegerField()),
                ('r4res', models.IntegerField()),
                ('r5res', models.IntegerField()),
                ('r6res', models.IntegerField()),
                ('r7res', models.IntegerField()),
                ('r8res', models.IntegerField()),
                ('r9res', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tournament')),
            ],
        ),
    ]
