# Generated by Django 3.2.13 on 2022-05-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20220427_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastratedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_res', models.FloatField()),
                ('stdev_res', models.FloatField()),
                ('firsts', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tournament')),
            ],
        ),
    ]
