from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UnsignedTournament(models.Model):
	name = models.CharField(max_length=30)
	date_conducted = models.DateField(auto_now=False, auto_now_add=False)
	num_players = models.IntegerField()
	has_tab = models.BooleanField()

class UnsignedPlayer(models.Model):
	name = models.CharField(max_length=20)
	surname = models.CharField(max_length=20)

class UnsignedRelation(models.Model):
	tournament = models.ForeignKey(UnsignedTournament, on_delete=models.CASCADE)
	player = models.ForeignKey(UnsignedPlayer, on_delete=models.CASCADE)
	r1 = models.IntegerField()
	r2 = models.IntegerField()
	r3 = models.IntegerField()
	r4 = models.IntegerField()
	r5 = models.IntegerField()
	r1pos = models.CharField(max_length=2)
	r2pos = models.CharField(max_length=2)
	r3pos = models.CharField(max_length=2)
	r4pos = models.CharField(max_length=2)
	r5pos = models.CharField(max_length=2)
	r1res = models.IntegerField()
	r2res = models.IntegerField()
	r3res = models.IntegerField()
	r4res = models.IntegerField()
	r5res = models.IntegerField()

class UnsignedOCMSLU(models.Model):
	tournament = models.ForeignKey(UnsignedTournament, on_delete=models.CASCADE)
	player = models.ForeignKey(UnsignedPlayer, on_delete=models.CASCADE)
	r1 = models.IntegerField()
	r2 = models.IntegerField()
	r3 = models.IntegerField()
	r4 = models.IntegerField()
	r5 = models.IntegerField()
	r6 = models.IntegerField()
	r7 = models.IntegerField()
	r8 = models.IntegerField()
	r9 = models.IntegerField()
	r1pos = models.CharField(max_length=2)
	r2pos = models.CharField(max_length=2)
	r3pos = models.CharField(max_length=2)
	r4pos = models.CharField(max_length=2)
	r5pos = models.CharField(max_length=2)
	r6pos = models.CharField(max_length=2)
	r7pos = models.CharField(max_length=2)
	r8pos = models.CharField(max_length=2)
	r9pos = models.CharField(max_length=2)
	r1res = models.IntegerField()
	r2res = models.IntegerField()
	r3res = models.IntegerField()
	r4res = models.IntegerField()
	r5res = models.IntegerField()
	r6res = models.IntegerField()
	r7res = models.IntegerField()
	r8res = models.IntegerField()
	r9res = models.IntegerField()

class UnsignedWeirdTournament(models.Model):
	tournament = models.ForeignKey(UnsignedTournament, on_delete=models.CASCADE)
	player = models.ForeignKey(UnsignedPlayer, on_delete=models.CASCADE)
	r1 = models.IntegerField()
	r2 = models.IntegerField()
	r3 = models.IntegerField()
	r4 = models.IntegerField()
	r5 = models.IntegerField()
	r6 = models.IntegerField()
	r1pos = models.CharField(max_length=2)
	r2pos = models.CharField(max_length=2)
	r3pos = models.CharField(max_length=2)
	r4pos = models.CharField(max_length=2)
	r5pos = models.CharField(max_length=2)
	r6pos = models.CharField(max_length=2)
	r1res = models.IntegerField()
	r2res = models.IntegerField()
	r3res = models.IntegerField()
	r4res = models.IntegerField()
	r5res = models.IntegerField()
	r6res = models.IntegerField()