# Generated by Django 3.2.13 on 2022-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourUnpack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsignedtournament',
            name='has_tab',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsignedtournament',
            name='num_players',
            field=models.IntegerField(default=36),
            preserve_default=False,
        ),
    ]
